name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
    steps:
    - name: Find the latest tag
      uses:  oprypin/find-latest-tag@v1
      with: 
        repository: htr3n/vaultwarden
      id: repo
    - name: Checkout
      uses: actions/checkout@v5
      with:
        ref: ${{ steps.repo.outputs.tag }}
    - name: Build Vaultwarden
      run: cargo build --features sqlite --release --verbose
    - name: Release Vaultwarden
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/vaultwarden
        tag_name: ${{ steps.repo.outputs.tag }}
